<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="POU_TestGit" Id="{c5094752-ef2e-424f-9a2a-bd7a94ebf4c3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU_TestGit
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_TestGit">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>