<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="POU_TestGit1" Id="{828f58be-d085-42d5-9082-bf4494704488}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU_TestGit1
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_TestGit1">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>